### ISSUE TITLE
Feature Request: Disk Advance Key

### ISSUE THREAD

**Issue by RobertTroughton** [MiSTer-devel/C64_MiSTer#100]
It would be fantastic if there could be a way to “silently” move to the next disk…

For example, if you have MementoMori-A.d64 loaded and press (eg. SHIFT+F12) it could automatically insert MementoMori-B.d64 (essentially, moving to the next char on the last char of the file name… A->B->C…, 1->2->…)

I want to record for YouTube from Mister and this would make it “cleaner” :-)

**Comment by RobertTroughton** [comment]
Chatted offline with dev - who believes the feature won’t be used..

**Comment by sorgelig** [comment]
Implementation will be complex due to many different ways to number the disks and numbers not always (i would say always not) at the end. It's also has to be done on HPS side (core cannot request for disk change) which means additional hot-key, additional key removed from core. Talking about feature in general HPS side should know which disk drive should be used to swap the disk. Many other unexpected circumstances are possible. All this hassle just to avoid couple button presses.

Also i think hiding MiSTer UI and pretend it as a real HW is not a good idea.
