### ISSUE TITLE
new exciting Transwarp crashes with DolphinDos on cores after 20210530

### ISSUE THREAD

**Issue by FRauANtjeK** [MiSTer-devel/C64_MiSTer#109]
Hi,

since core 20210607 "Transwarp" crashes with DolphinDos Kernal and parallel cable enabled.

Kernal 20210530 works, so maybe some code for the parallel cable has been changed between those two kernals?

**Comment by KrillPlush** [comment]
What stumps me is that the problem doesn't appear when either disabling the parallel connection in hardware (MiSTer configuration) or disabling parallel communication in software (@XP-).

The latter hints that there are some software registers to set correctly, but the drive-side parallel port should be set to all-input already, and the C-64 side to all-output. So there should be no reason for the JMP ($DD00) with $DD01 set to $E0 to end up anywhere else than $E0xy, regardless of a parallel cable or not, and yet it seems to do that.

**Comment by KrillPlush** [comment]
C-64 side. Note that $DD00 is the serial port (mostly, with bit 2 going out to parallel cable), while $DD01 is the parallel port.

The idea is to react to incoming serial signals quicker (with less jitter) than with a polling loop, and $DD01 is expected to read $E0 when doing JMP ($DD00). Hence it is set to all-outputs ($DD03 <= $ff) before being initialised ($DD01 <= $E0).

**Comment by sorgelig** [comment]
ok, at first core implements the bus with open collector, so any party driving signal low will win. If no one drives low, then it will be 1.
I need to check further if anyone drives it low unexpectedly..

**Comment by sorgelig** [comment]
i'm going to sleep now. Will walk through commits tomorrow.

**Comment by KrillPlush** [comment]
It has been reported to work without problems on a C-64 with DolphinDOS. (Can't test it myself because no DolphinDOS, but i trust the reporters.)

When trying out things before, did you set the disk_parport side or the disk_access side of the check to true, or maybe both?
(Tying the decision to the drive LED is obviously wrong, but i guess that's why it was changed in the first place.)

I'm rather sure there is no temporal bug in the C-64 code.

And there is no parallel communication to begin with, nor a need for the drive code to set up things.
The C-64 side sets $DD01 to all-output with value $E0, and external signals (e.g., by a parallel cable that happens to be connected) should not be able to change that value. (With some TTL driver on the real C-64's user port, external signals can override the output setting, but that's what the initial compatibility check is guarding against.)

Furthermore, the drive side has the parallel port on all-inputs at the point of crashing, with or without DolphinDOS.

There is one interesting thing i noticed in the meanwhile:
Between the compatibility check and the crash-failure, the drive code is uploaded, via DolphinDOS and parallel connection.
Now, DolphinDOS is well-behaved, buffering and restoring $DD01 and $DD03:
```
.C:f1b8  AD 03 DD    LDA $DD03
.C:f1bb  8D 96 02    STA $0296
.C:f1be  A9 FF       LDA #$FF
.C:f1c0  8D 03 DD    STA $DD03
.C:f1c3  AD 01 DD    LDA $DD01
.C:f1c6  8D 95 02    STA $0295

.C:f95f  AD 0C DC    LDA $DC0C
.C:f962  29 02       AND #$02
.C:f964  8D 0C DC    STA $DC0C
.C:f967  AD 96 02    LDA $0296
.C:f96a  8D 03 DD    STA $DD03
.C:f96d  AD 95 02    LDA $0295
.C:f970  8D 01 DD    STA $DD01
```
It might be that, for some reason (could be a long-standing bug in another component, triggered now), a wrong value is read from $DD01 when buffering, and then later written back.

**Comment by KrillPlush** [comment]
Such a communication sync point is in place already.

But good point about the previous drive LED gate, which might have shielded off an emulated-drive-side bug before being removed.

I will have a closer look at the DolphinDOS drive-side ROM and also the MiSTer VIA6522 implementation.

But i still have no theory how the all-outputs C-64 side of the parallel port is overridden (by external forces majeures?) to something else.

**Comment by sorgelig** [comment]
I've checked C64 schematics - it uses open collector bus, so there is no competition of signals. So the one driving low wins.

**Comment by sorgelig** [comment]
this is build with drive_led used as gate:
[C64.zip](https://github.com/MiSTer-devel/C64_MiSTer/files/7376797/C64.zip)

May be it will help you to debug.

**Comment by sorgelig** [comment]
According to MOS6526 datasheet it uses both 0 and 1 drivers on output. So it's possible it competes with VIA on drive side. On real HW CIA will win in you read the bus on C64 side, and VIA will win if you will read the bus on drive side. Simply because cable and PCB traces have some resistance. Although it's a bad sign for real HW because your loader will put both sides into competition mode overloading their outputs.

**Comment by sorgelig** [comment]
i think issue can be considered as solved.

**Comment by KrillPlush** [comment]
Some parallel cables do provide proper buffering. I guess those would not change the read-output-value behaviour as observed with two naked chips connected, though.
