### ISSUE TITLE
Feature Request: Warp mode

### ISSUE THREAD

**Issue by Jammmmm** [MiSTer-devel/C64_MiSTer#169]
In emulation I could "Warp" the system speed (Vice = ALT+W) so everything runs significantly faster.

Any chance of seeing that in this core?

I'm not sure how MiSTer works on the software side of things so I'm not sure if it's possible seeing as how accuracy (including performance) is what it strives for.

**Comment by sorgelig** [comment]
C64 core provides turbo mode. This is the only turbo you can have.
You can't expect all features from emulators on FPGA.

**Comment by Jammmmm** [comment]
I'm definitely not expecting everything from an emulator. I'm very grateful for what you've already given us :)

I'll play with the turbo mode again. I couldn't get it working before but I'll figure it out.

**Comment by sorgelig** [comment]
Not every game may benefit from turbo mode because it makes only CPU to work faster while other components work as usual. If game syncs output to vertical retrace, then it will work as before. Turbo only helpful for games struggling with original C64 performance.
Emulator may increase speed of whole C64 including higher FPS

**Comment by Jammmmm** [comment]
Oh! It's just CPU. That makes sense as to why I saw nothing happen. Thanks for the explanation!
